### ISSUE TITLE
Getting TS error Transformer<Root, Root>' is not assignable to type 'Plugin<any[], any, any>'.

### ISSUE THREAD

**Issue by khanakia** [atomiks/rehype-pretty-code#145]
I am getting the below error however the code works fine when I compile

```js
import { MDXRemote } from 'next-mdx-remote/rsc';
import rehypePrettyCode from 'rehype-pretty-code';


export default async function Page({ params }: any) {
  return (
    <MDXRemote
    source={`test`}
    options={{
      mdxOptions: {
        rehypePlugins: [rehypePrettyCode],
      },
    }}
  />
  );
}
```

![Screenshot 2023-12-23 at 10 36 19 PM](https://github.com/atomiks/rehype-pretty-code/assets/2174170/d11a385a-9f38-42b9-a073-91945b48bf01)

**Comment by o-az** [comment]
This type error is because `next-mdx-remote` uses an old version of `vfile`.

The main issue in your example is:

```sh
Type 'VFileMessage' is missing the following properties from type 'VFileMessage': ancestors
```

[`vfile`](https://github.com/vfile/vfile) v6 has those properties whereas v5.3 which `next-mdx-remote` uses doesn't. So the issue is `next-mdx-remote` is using an older version of `vfile` dependency:

https://github.com/hashicorp/next-mdx-remote/blob/main/package.json#L17

`rehype-pretty-code` uses the latest version of `unified` which has `vfile` ^6 as a dependency:

https://github.com/unifiedjs/unified/blob/b69689bba52a918d87aa62f295ccffa8d9aa8ef8/package.json#L54

cc @atomiks

**Comment by atomiks** [comment]
Seems that `next-mdx-remote` should update to latest `unified`/`vfile` dependencies. For now, you can ignore the type error since runtime works fine.
