### ISSUE TITLE
Differentiate multiple highlighted words

### ISSUE THREAD

**Issue by atomiks** [atomiks/rehype-pretty-code#54]
Like the new React docs:

<img width="921" alt="Screenshot 2023-01-01 at 11 09 38 pm" src="https://user-images.githubusercontent.com/22450188/210170117-04054207-f56b-4543-af03-25d7c4165017.png">

---

I don't think there's a (n easy?) way to differentiate the instances, see:

<img width="722" alt="Screenshot 2023-01-01 at 11 09 48 pm" src="https://user-images.githubusercontent.com/22450188/210170123-f672f270-1a31-422f-bb63-f6cbacf75adb.png">

**Comment by khinshankhan** [comment]
Hello, this does seem tough. 

So I got part of the react docs example working (see picture at the bottom). Firstly, css tricks like counter or nth-child or nth-of-type can't be used, so I looked to see if we could to it with js at build time. We can, sort of. I have the following for the options:
```js
let count = 0;
const rehypePrettyCodeOptions: Partial<Options> = {
  // Use one of Shiki's packaged themes
  theme: {
    light: "github-light",
    dark: "github-dark-dimmed",
  },
  onVisitLine(node) {
    // Prevent lines from collapsing in `display: grid` mode, and
    // allow empty lines to be copy/pasted
    if (node.children.length === 0) {
      node.children = [{ type: "text", value: " " }];
    }
    count = 0;
  },

  onVisitHighlightedLine: (node) => {
    node.properties.className.push("highlighted");
  },
  onVisitHighlightedWord: (node) => {
    console.log({ node, ...node, count });
    node.properties.style = ""; // inline has more specificity than class names, so just reset
    node.properties.className = [`word-highlighted-${count}`];
    count += 1;
  },
};
```
The idea is in per line, every highlighted instance gets the class with the count incremented by 1 per word highlight instance, and reset the count every time we visit a new line. The count variable is shared between the two functions. It's probably some violation of pure functions, but it works :shrug:

Then in my styles I threw in, don't mind the colors I tried choosing similar to the react example:
```css
  "code > span.line > span.word-highlighted-0": {
    color: "steelblue",
    backgroundColor: "paleturquoise",
  },
  "code > span.line > span.word-highlighted-1": {
    color: "brown",
    backgroundColor: "bisque",
  },
  "code > span.line > span.word-highlighted-2": {
    color: "indigo",
    backgroundColor: "orchid",
  },
```
I'm using stitches, which is a lightweight css in js, but the actual css would just be removing the quotes colons and commas. You'll have to set styles for as many instances of matches per line you may have per line. You can use `code > span.line > span[class^='word-highlighted-']` to apply a style to any words highlighted regardless of count. If you throw that before specific numbers, you'll have a catchall style.

Note: I'm pretty sure instead of setting a class, you could just set the styles in `onVisitHighlightedLine` so they'll be inline. I find classes more debuggable personally though. In fact, I found some cases based on this, more below.
 
This would be the react example codeblock (codeblock of a codeblock):
```
    ```js showLineNumbers /age/ /name/ /setAge/ /setName/ /42/ /'Taylor'/
    import { useState } from 'react';
    
    function MyComponent() {
        const[age, setAge] = useState(42)
        const[name, setName] = useState('Taylor')
        // ...
    ```
```

This is dandy and all, but to be clear, this is a hack. Internally, I think rehype goes through the literals one by one per line, which means `onVisitHighlightedWord` could get called twice for a literal if it matches the first time and then the third call would be the second literal even if that's not the order in the codeblock.

This bleeds into another issue with the method: not just the count, but the order of literals matters. Here's a codeblock of a codeblock showing both issues (also in image since visuals are so much easier): 
```
    ```js {2} showLineNumbers /carrot/ /apple/
    console.log("carrot carrot mango apple")
    console.log("carrot carrot mango apple")
    console.log("carrot carrot carrot mango apple")
    console.log("carrot apple mango carrot")
    ```
```

Image!
![image](https://user-images.githubusercontent.com/22206867/211113118-fccbb6b3-f546-4a0a-ba65-cea88587ef86.png)


Maybe if rehype is refactored to use a single regex instead of multiple literals, this would work perfectly(?)

**Comment by atomiks** [comment]
@khinshankhan nice post! I think we need to allow an identifier after the regex like this:

````
    ```js showLineNumbers /age/a /name/a /setAge/b /setName/b /42/c /'Taylor'/c
    import { useState } from 'react';
    
    function MyComponent() {
        const [age, setAge] = useState(42);
        const [name, setName] = useState('Taylor');
        // ...
    ```
````

Then in `onVisitHighlightedWord`, it passes in that identifier as a parameter (so `a`, `b`, or `c`). This would allow you to color it based on the identifier.

```js
onVisitHighlightedWord(node, id) {
  node.properties.style = `color: ${{a: 'red', b: 'blue', c: 'green'}[id]}`;
}
```

**Comment by khinshankhan** [comment]
Nice. Yep, this'll allow nice control on a word basis :+1:
